artifacts_root: artifacts


data_validation:
  root_dir: artifacts/data_validation
  raw_data_dir: artifacts/data_ingestion/dados.csv
  status_file: artifacts/data_validation/status.txt



data_transformation:
  raw_data_path: artifacts/data_ingestion/dados.csv
  transformed_data_path: artifacts/data_transformation



model_trainer:
  model_target_dir: artifacts/model_output
  train_x_data_path: artifacts/data_transformation/X_train_transformed.csv
  test_x_data_path: artifacts/data_transformation/X_test_transformed.csv
  train_y_data_path: artifacts/data_transformation/y_train.csv
  test_y_data_path: artifacts/data_transformation/y_test.csv
  model_name: model.joblib



model_evaluation:
  model_results_dir: artifacts/model_evaluation
  test_x_data_path: artifacts/data_transformation/X_test_transformed.csv
  test_y_data_path: artifacts/data_transformation/y_test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json






