artifacts_root: artifacts


data_validation:
  root_dir: artifacts/data_validation
  raw_data_dir: artifacts/data_ingestion/dados.csv
  status_file: artifacts/data_validation/status.txt



data_transformation:
  raw_data_path: artifacts/data_ingestion/dados.csv
  transformed_data_path: artifacts/data_transformation



# model_trainer:
#   root_dir: artifacts/model_trainer
#   train_data_path: artifacts/data_transformation/train.csv
#   test_data_path: artifacts/data_transformation/test.csv
#   model_name: model.joblib



# model_evaluation:
#   root_dir: artifacts/model_evaluation
#   test_data_path: artifacts/data_transformation/test.csv
#   model_path: artifacts/model_trainer/model.joblib
#   metric_file_name: artifacts/model_evaluation/metrics.json






